### ISSUE TITLE
Fileupload isn't working anymore

### ISSUE THREAD

**Issue by tedstriker** [zetxx/node-red-node-file-upload#1]
When triggered, it throws following error in NodeRed 0.11.2 / nodes 0.12.4:

`25 Oct 14:59:25 - Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at upload (/nodered/.node-red/node_modules/node-red-node-file-upload/node_modules/poster/lib/poster.js:29:30)
    at /nodered/.node-red/node_modules/node-red-node-file-upload/node_modules/poster/lib/poster.js:288:15
    at FSReqWrap.oncomplete (fs.js:95:15)
`

**Comment by zetxx** [comment]
if you are interested in submitting pull request i will merge it asap

**Comment by tedstriker** [comment]
Thanks for your offer. Further investigation showed that the problem exists within the dependency "poster.js". Your node file-upload remains fine and unchanged.

**Comment by zetxx** [comment]
ok, if needed, make pull and i will merge it
